from yandex_testing_lesson import (Rectangle, Rectangleimport, TypeError,
                                   ValueError, 0, 0def, 1, 1.5, 1], 1def, 2,
                                   2], 3], 4def, 5, 6def, 10, 10.5, 30, 50def,
                                   52.5def, '1', '1.5', -1, .get_area,
                                   .get_perimeter, :, ==, [1, ['1.5', assert,
                                   def, pytest.raises, pytestdef,
                                   test_area_border_all,
                                   test_area_border_first,
                                   test_area_border_right,
                                   test_area_border_second, test_area_float,
                                   test_area_int, test_negative_all,
                                   test_negative_first, test_negative_second,
                                   test_perimeter_border, test_perimeter_float,
                                   test_perimeter_right, test_perimeter_zero,
                                   test_type_iterable_object_all,
                                   test_type_iterable_object_first,
                                   test_type_iterable_object_second,
                                   test_type_str_all, test_type_str_first,
                                   test_type_str_second, with)
